version: '3.9'

services:
  pyllama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyllama
    ports:
      - '8000:8000'
    depends_on:
      - redis-master
      - redis-replica
    environment:
      - REDIS_PASSWORD=SuperSecret
  redis-master:
    image: 'bitnami/redis:7.0'
    container_name: redis-master
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=SuperSecret
    volumes:
      - redis-data:/bitnami/redis/data

  redis-replica:
    image: 'bitnami/redis:7.0'
    container_name: redis-replica
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=SuperSecret
      - REDIS_PASSWORD=SuperSecret2

volumes:
  redis-data:
    driver: local